test

diff --git a/buildenv/jenkins/jck_sync b/buildenv/jenkins/jck_sync
--- a/buildenv/jenkins/jck_sync
+++ b/buildenv/jenkins/jck_sync
@@ -338,12 +338,12 @@ def target_JCK_Folder(){
                     sh "cat ${logFile}"
                         
                     // Use 'grep' to check if any new folders are detected
-                    def grepCommand = "grep -c '${specificLine1}' ${logFile}"
-                    def grepResult = sh(script: grepCommand, returnStdout: true)
-                    def exitCode = sh(script: "echo \$?", returnStatus: true)
-                    if (exitCode != 0) {
-                        echo "An error occurred while running grep: Exit code ${exitCode}"
-                    }
+                    def grepCommand = "grep '${specificLine1}' ${logFile} || true"
+                    def grepResult = sh(script: grepCommand, returnStatus: true)
+                    //def exitCode = sh(script: "echo \$?", returnStatus: true)
+                    // if (exitCode != 0) {
+                    //     echo "An error occurred while running grep: Exit code ${exitCode}"
+                    // }
                     //echo  "grepResult= ${grepResult}"
                     //def count = grepResult.toInteger()
 
@@ -359,11 +359,11 @@ def target_JCK_Folder(){
                     // if (params.JDK_VERSION == "8"){
                     //     count = 3
                     // }
-                    if (grepResult.toInteger() == 0)  {
-                        echo "Specific line not found in the log file: '${specificLine}'"
+                    if (grepResult == 0)  {
+                        echo "Specific line  found in the log file: '${specificLine}'"
                         COMMENT="No new folders detected. No need to update playlist.xml \\r\\n ``` ${commentBody} ``` "
                     } else {
-                        echo "Specific line  found in the log file : '${specificLine}'"
+                        echo "Specific line not found in the log file : '${specificLine}'"
                         COMMENT="New folders detected. Need to update playlist.xml \\r\\n ``` ${commentBody} ``` "
                     }
                 }
